// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxANPtHQznN-oGBVcTso_U3GZemHvGILE',
    appId: '1:745672144550:web:107f8d00945cfd7fd2a667',
    messagingSenderId: '745672144550',
    projectId: 'mychatapp-7477b',
    authDomain: 'mychatapp-7477b.firebaseapp.com',
    storageBucket: 'mychatapp-7477b.appspot.com',
    measurementId: 'G-L8EFXN4JRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7eOqcpVlOkg6uiWx9rYKGC2Hdq5Uo3E',
    appId: '1:745672144550:android:e49f602f12d62a6fd2a667',
    messagingSenderId: '745672144550',
    projectId: 'mychatapp-7477b',
    storageBucket: 'mychatapp-7477b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkq7JrP5jsoQqWlNp1v64RXXKlBMN5QD8',
    appId: '1:745672144550:ios:7b65c57f929e2279d2a667',
    messagingSenderId: '745672144550',
    projectId: 'mychatapp-7477b',
    storageBucket: 'mychatapp-7477b.appspot.com',
    iosClientId: '745672144550-dim8fq65l43esjnpmssi94kb5erl9i64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkq7JrP5jsoQqWlNp1v64RXXKlBMN5QD8',
    appId: '1:745672144550:ios:7b65c57f929e2279d2a667',
    messagingSenderId: '745672144550',
    projectId: 'mychatapp-7477b',
    storageBucket: 'mychatapp-7477b.appspot.com',
    iosClientId: '745672144550-dim8fq65l43esjnpmssi94kb5erl9i64.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
